### ISSUE TITLE
[Android] Set up SDK

### ISSUE THREAD

**Issue by vegeta2102** [plaidev/karte-technical-support#2]
Hi !
I am trying to set up Karte as below document.
https://developers.karte.io/docs/setup-android-sdk

Basically , It's working fine. But, It is not recommended to setting like below in Android project : 
 `implementation 'io.karte.android:tracker:1.4.+'`

Base on Android document, we should specific version of repo such as : `1.4.0 or 1.4.8`
If we use plus (+) , repo will be always get with latest version. ( There may be some conflict problem with other for the future ). 

Have you considered about this ?

**Comment by tomoponzoo** [comment]
@vegeta2102 
Yes, if you want to avoid unpredictable and unrepeatable build, you should use specific version.
But we use `+` in the document because our SDK has support period and we want developers to use the latest version of SDK anytime.

**Comment by vegeta2102** [comment]
@tomoponzoo 
Thank you for the reply !
Sure, I think I have to consider to use specific version. If we always get the latest version, there may be some method will be deprecated or the usage will be changed !

**Comment by vegeta2102** [comment]
@tomoponzoo 
By the way, what is the latest stable version of Karte Android should I use now?

**Comment by takaaki7** [comment]
@vegeta2102 Hi.
We don't classify sdk versions as stable or not stable. Simply we recommend developers to use the latest version. 
You can find the latest version in that release note.(currently `1.4.7`)
