### ISSUE TITLE
Push Notification - How to confirm FCM token has been send or not

### ISSUE THREAD

**Issue by vegeta2102** [plaidev/karte-technical-support#3]
I have 2 questions : 
1. FirebaseInstanceIdService class is deprecated
FirebaseInstanceIdService class is deprecated in Firebase recently. So we have to change the implement way such as : 
https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdServic
https://medium.com/android-school/firebaseinstanceidservice-is-deprecated-50651f17a148

2. How to check FCM token has been send to Karte?
As far as I know, whenever token has been changed ( onNewToken method is invoked) we have to get new FCM token and send to Karte : 
`trackFcmToken(token);`
**KarteFirebaseInstanceIdService.class**  
```
public abstract class KarteFirebaseInstanceIdService extends FirebaseInstanceIdService {
    public KarteFirebaseInstanceIdService() {
    }

    public static String getToken() {
        return FirebaseInstanceId.getInstance().getToken();
    }

    public void onTokenRefresh() {
        String refreshedToken = getToken();
        this.sendToken(refreshedToken);
    }

    private void sendToken(String token) {
        Tracker tracker = this.getTracker();
        if (tracker == null) {
            Log.i("KarteTracker", "tracker is uninitialized");
        } else {
            tracker.trackFcmToken(token);
        }
    }

    protected abstract Tracker getTracker();
}
```
Link : https://developers.karte.io/docs/receive-notification-android-sdk
So, how can I check the token has already send to Karte via `tracker.trackFcmToken(token)`

I hope there is a public method in SDK to check this . It can be look like : 

```
public static String getFcmToken() {
    if (token.isNullOrEmpty()) {
        return "Token has not been set";
    }
    return token;
}
```
Actually, there was a problem that I can not receive push notification from Karte so I want to check that the token is send or not and basically trace where/when does the problem occur ???

Here is the docs I already read !
https://developers.karte.io/docs/receive-notification-android-sdk
KARTE for Appプッシュ通知で問題が発生した時のチェックリスト
https://support2.karte.io/start/karte-for-app-faq/9011/#index-3
https://support2.karte.io/start/karte-for-app-faq/8995/
https://support2.karte.io/campaign/campaign-popup/campaign-popup-description/1665/

**Comment by takaaki7** [comment]
#### 1
Thank you for reporting.
We are planning to release new version sdk that doesn't depend on deprecated method before long. Sorry for the trouble.

#### 2
You can check FCM token on the KARTE dashboard.
I've added a description to how to check it to this document.
https://support2.karte.io/start/karte-for-app-faq/9011/#fcm-3

I will close this issue, but if you cannot resolve the problem feel free to reopen this.

**Comment by vegeta2102** [comment]
Thanks!
You saved my time.
