### ISSUE TITLE
How can I do testing of rich notification?

### ISSUE THREAD

**Issue by yukihiro-yukki-sato** [plaidev/karte-technical-support#6]
Hi.
I have implemented rich notification on iOS with referring to the following URL.
https://developers.karte.io/docs/receive-rich-notification-ios-sdk

I would like to test sending the notification.
However, I can't find guides of sending rich notification.
And I tried to send image file by "Talk" function, however, I couldn't receive rich notification(but normal notification has be received).

How can I do testing of rich notification?

**Comment by tomoponzoo** [comment]
@yukihiro-yukki-sato 
日本の方のようでしたので、日本語でコメントさせていただきます。

Talk機能から送信する通知については、通知の到達確認を目的としたものであり、こちらではリッチ通知の検証は行えません。
そのためリッチ通知の検証を行いたい場合は、実際に接客サービスを作成し、テストユーザーに対して配信を行うというステップを踏む必要があります。

接客サービスの作成方法及びプッシュ通知接客の設定方法については、下記サポートサイトをご確認ください。

[接客サービスの作成・編集方法 | ドキュメント / 接客サービス / 作成・ 配信設定 | KARTEサポートサイト](https://support.karte.io/post/4zDHCDjsdsB42yaCsPQ1br)

[アプリプッシュ通知の設定方法 | ドキュメント / 接客タイプ / アプリプッシュ | KARTEサポートサイト](https://support.karte.io/post/4Kz7x02d58IADB99RjIfr8#4-0)

**Comment by yukihiro-yukki-sato** [comment]
@tomoponzoo 
ご返答ありがとうございます。

Talkでは検証不可であること承知いたしました。
ご回答頂いた方法でリッチ通知が送信できることを確認できましたのでクローズさせていただきます。

お手数をおかけ致しました。
ありがとうございます。
