### ISSUE TITLE
How Karte count MAU?

### ISSUE THREAD

**Issue by khuongdo** [plaidev/karte-technical-support#7]
My company has received a notification from Karte that our MAU (Monthly Active User) exceeded the the limitation by the contract (about 400000 users) .
Could you explain how Karte count MAU (by tags or sth else)? 
So we can optimize the way we implement Karte in our system.
Thanks.

**Comment by tikidunpon** [comment]
@khuongdo 

Sorry for late replying, please contact us via the chat room in the admin page for your question.

The chat button are located following in admin page.

Global Navigation > Question mark icon > Ask question on chat
