### ISSUE TITLE
画面の境界を認識する条件に関して

### ISSUE THREAD

**Issue by KeitaOno-rakuten-lifullstay** [plaidev/karte-technical-support#8]
[Viewイベントの発火](https://developers.karte.io/docs/concepts-boundary-transition-ios-sdk-v2#view%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%81%AE%E7%99%BA%E7%81%AB)
> Viewイベントの発火（viewメソッドの呼び出し）が行われた時点で画面の境界を認識します。

こちらに関してなのですが、具体的には `Tracker.view(〜)` メソッドのことであっていますか？

例えばですが、SwiftUIなどを使って実装した場合、`UIViewController` 系の画面遷移のイベントが発生しないため、明示的にTracker.viewを呼ぶことで画面の境界を認識させることができるという認識であっていますでしょうか？

お手数おかけしますがご回答いただければ幸いです。

**Comment by KeitaOno-rakuten-lifullstay** [comment]
https://github.com/plaidev/karte-technical-support/issues/7#issuecomment-702508856

> The chat button are located following in admin page. https://admin.karte.io/


Sorry I'll close this issue.

**Comment by wasnot** [comment]
@KeitaOno-rakuten-lifullstay 
お問合せいただきありがとうございます。
念の為、こちらでも回答させていただきます。

ご認識の通り、SwiftUI等、UIKitの画面遷移が発生しないアプリにおいては、Viewイベントを発火することで画面境界として認識され、アプリ内メッセージの非表示処理等が行われます。

Viewイベントに関しましては、ご指摘のとおり基本的に`Tracker.view()`メソッドにより発火していただくことになると思います。
また、下記ページにも記載あります通り、Tracker.trackメソッドでも`Tracker.track("view", values: ...)`などと呼び出すことで同等のイベントが発火可能です。
[画面の表示イベントを送信する](https://developers.karte.io/docs/appendix-usage-tracking-ios-sdk-v2#%E7%94%BB%E9%9D%A2%E3%81%AE%E8%A1%A8%E7%A4%BA%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%82%92%E9%80%81%E4%BF%A1%E3%81%99%E3%82%8B)

ご参考になりましたら幸いです。
他にもご不明点等ありましたら、お問合せください。

**Comment by KeitaOno-rakuten-lifullstay** [comment]
@wasnot 
ご回答頂きありがとうございます！非常に助かりました。
